/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDaybookRouteImport } from './routes/_authenticated/daybook'
import { Route as AuthenticatedTransferIndexRouteImport } from './routes/_authenticated/transfer.index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated/people.index'
import { Route as AuthenticatedOutgoingIndexRouteImport } from './routes/_authenticated/outgoing.index'
import { Route as AuthenticatedIncomingIndexRouteImport } from './routes/_authenticated/incoming.index'
import { Route as AuthenticatedFinancesIndexRouteImport } from './routes/_authenticated/finances.index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics.index'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsPreferencesRouteImport } from './routes/_authenticated/settings.preferences'
import { Route as AuthenticatedReportsTransferStockRouteImport } from './routes/_authenticated/reports.transfer-stock'
import { Route as AuthenticatedReportsOutgoingRouteImport } from './routes/_authenticated/reports.outgoing'
import { Route as AuthenticatedReportsIncomingRouteImport } from './routes/_authenticated/reports.incoming'
import { Route as AuthenticatedPeopleIdRouteImport } from './routes/_authenticated/people.$id'
import { Route as AuthenticatedOutgoingEditHistoryRouteImport } from './routes/_authenticated/outgoing.edit-history'
import { Route as AuthenticatedOutgoingIdRouteImport } from './routes/_authenticated/outgoing.$id'
import { Route as AuthenticatedIncomingEditHistoryRouteImport } from './routes/_authenticated/incoming.edit-history'
import { Route as AuthenticatedIncomingIdRouteImport } from './routes/_authenticated/incoming.$id'
import { Route as AuthenticatedAnalyticsVarietyBreakdownRouteImport } from './routes/_authenticated/analytics.variety-breakdown'
import { Route as AuthenticatedAnalyticsAdvancedRouteImport } from './routes/_authenticated/analytics.advanced'
import { Route as AuthenticatedPeopleIdIndexRouteImport } from './routes/_authenticated/people.$id.index'
import { Route as AuthenticatedPeopleIdReportRouteImport } from './routes/_authenticated/people.$id.report'
import { Route as AuthenticatedFinancesLedgersIdRouteImport } from './routes/_authenticated/finances.ledgers.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDaybookRoute = AuthenticatedDaybookRouteImport.update({
  id: '/daybook',
  path: '/daybook',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransferIndexRoute =
  AuthenticatedTransferIndexRouteImport.update({
    id: '/transfer/',
    path: '/transfer/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOutgoingIndexRoute =
  AuthenticatedOutgoingIndexRouteImport.update({
    id: '/outgoing/',
    path: '/outgoing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncomingIndexRoute =
  AuthenticatedIncomingIndexRouteImport.update({
    id: '/incoming/',
    path: '/incoming/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesIndexRoute =
  AuthenticatedFinancesIndexRouteImport.update({
    id: '/finances/',
    path: '/finances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPreferencesRoute =
  AuthenticatedSettingsPreferencesRouteImport.update({
    id: '/settings/preferences',
    path: '/settings/preferences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsTransferStockRoute =
  AuthenticatedReportsTransferStockRouteImport.update({
    id: '/reports/transfer-stock',
    path: '/reports/transfer-stock',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsOutgoingRoute =
  AuthenticatedReportsOutgoingRouteImport.update({
    id: '/reports/outgoing',
    path: '/reports/outgoing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIncomingRoute =
  AuthenticatedReportsIncomingRouteImport.update({
    id: '/reports/incoming',
    path: '/reports/incoming',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPeopleIdRoute = AuthenticatedPeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOutgoingEditHistoryRoute =
  AuthenticatedOutgoingEditHistoryRouteImport.update({
    id: '/outgoing/edit-history',
    path: '/outgoing/edit-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOutgoingIdRoute = AuthenticatedOutgoingIdRouteImport.update({
  id: '/outgoing/$id',
  path: '/outgoing/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomingEditHistoryRoute =
  AuthenticatedIncomingEditHistoryRouteImport.update({
    id: '/incoming/edit-history',
    path: '/incoming/edit-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncomingIdRoute = AuthenticatedIncomingIdRouteImport.update({
  id: '/incoming/$id',
  path: '/incoming/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsVarietyBreakdownRoute =
  AuthenticatedAnalyticsVarietyBreakdownRouteImport.update({
    id: '/analytics/variety-breakdown',
    path: '/analytics/variety-breakdown',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsAdvancedRoute =
  AuthenticatedAnalyticsAdvancedRouteImport.update({
    id: '/analytics/advanced',
    path: '/analytics/advanced',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPeopleIdIndexRoute =
  AuthenticatedPeopleIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPeopleIdRoute,
  } as any)
const AuthenticatedPeopleIdReportRoute =
  AuthenticatedPeopleIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedPeopleIdRoute,
  } as any)
const AuthenticatedFinancesLedgersIdRoute =
  AuthenticatedFinancesLedgersIdRouteImport.update({
    id: '/finances/ledgers/$id',
    path: '/finances/ledgers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/daybook': typeof AuthenticatedDaybookRoute
  '/analytics/advanced': typeof AuthenticatedAnalyticsAdvancedRoute
  '/analytics/variety-breakdown': typeof AuthenticatedAnalyticsVarietyBreakdownRoute
  '/incoming/$id': typeof AuthenticatedIncomingIdRoute
  '/incoming/edit-history': typeof AuthenticatedIncomingEditHistoryRoute
  '/outgoing/$id': typeof AuthenticatedOutgoingIdRoute
  '/outgoing/edit-history': typeof AuthenticatedOutgoingEditHistoryRoute
  '/people/$id': typeof AuthenticatedPeopleIdRouteWithChildren
  '/reports/incoming': typeof AuthenticatedReportsIncomingRoute
  '/reports/outgoing': typeof AuthenticatedReportsOutgoingRoute
  '/reports/transfer-stock': typeof AuthenticatedReportsTransferStockRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/finances/': typeof AuthenticatedFinancesIndexRoute
  '/incoming/': typeof AuthenticatedIncomingIndexRoute
  '/outgoing/': typeof AuthenticatedOutgoingIndexRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/transfer/': typeof AuthenticatedTransferIndexRoute
  '/finances/ledgers/$id': typeof AuthenticatedFinancesLedgersIdRoute
  '/people/$id/report': typeof AuthenticatedPeopleIdReportRoute
  '/people/$id/': typeof AuthenticatedPeopleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/daybook': typeof AuthenticatedDaybookRoute
  '/analytics/advanced': typeof AuthenticatedAnalyticsAdvancedRoute
  '/analytics/variety-breakdown': typeof AuthenticatedAnalyticsVarietyBreakdownRoute
  '/incoming/$id': typeof AuthenticatedIncomingIdRoute
  '/incoming/edit-history': typeof AuthenticatedIncomingEditHistoryRoute
  '/outgoing/$id': typeof AuthenticatedOutgoingIdRoute
  '/outgoing/edit-history': typeof AuthenticatedOutgoingEditHistoryRoute
  '/reports/incoming': typeof AuthenticatedReportsIncomingRoute
  '/reports/outgoing': typeof AuthenticatedReportsOutgoingRoute
  '/reports/transfer-stock': typeof AuthenticatedReportsTransferStockRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/finances': typeof AuthenticatedFinancesIndexRoute
  '/incoming': typeof AuthenticatedIncomingIndexRoute
  '/outgoing': typeof AuthenticatedOutgoingIndexRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/transfer': typeof AuthenticatedTransferIndexRoute
  '/finances/ledgers/$id': typeof AuthenticatedFinancesLedgersIdRoute
  '/people/$id/report': typeof AuthenticatedPeopleIdReportRoute
  '/people/$id': typeof AuthenticatedPeopleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/daybook': typeof AuthenticatedDaybookRoute
  '/_authenticated/analytics/advanced': typeof AuthenticatedAnalyticsAdvancedRoute
  '/_authenticated/analytics/variety-breakdown': typeof AuthenticatedAnalyticsVarietyBreakdownRoute
  '/_authenticated/incoming/$id': typeof AuthenticatedIncomingIdRoute
  '/_authenticated/incoming/edit-history': typeof AuthenticatedIncomingEditHistoryRoute
  '/_authenticated/outgoing/$id': typeof AuthenticatedOutgoingIdRoute
  '/_authenticated/outgoing/edit-history': typeof AuthenticatedOutgoingEditHistoryRoute
  '/_authenticated/people/$id': typeof AuthenticatedPeopleIdRouteWithChildren
  '/_authenticated/reports/incoming': typeof AuthenticatedReportsIncomingRoute
  '/_authenticated/reports/outgoing': typeof AuthenticatedReportsOutgoingRoute
  '/_authenticated/reports/transfer-stock': typeof AuthenticatedReportsTransferStockRoute
  '/_authenticated/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/finances/': typeof AuthenticatedFinancesIndexRoute
  '/_authenticated/incoming/': typeof AuthenticatedIncomingIndexRoute
  '/_authenticated/outgoing/': typeof AuthenticatedOutgoingIndexRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/transfer/': typeof AuthenticatedTransferIndexRoute
  '/_authenticated/finances/ledgers/$id': typeof AuthenticatedFinancesLedgersIdRoute
  '/_authenticated/people/$id/report': typeof AuthenticatedPeopleIdReportRoute
  '/_authenticated/people/$id/': typeof AuthenticatedPeopleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/daybook'
    | '/analytics/advanced'
    | '/analytics/variety-breakdown'
    | '/incoming/$id'
    | '/incoming/edit-history'
    | '/outgoing/$id'
    | '/outgoing/edit-history'
    | '/people/$id'
    | '/reports/incoming'
    | '/reports/outgoing'
    | '/reports/transfer-stock'
    | '/settings/preferences'
    | '/settings/profile'
    | '/analytics/'
    | '/finances/'
    | '/incoming/'
    | '/outgoing/'
    | '/people/'
    | '/settings/'
    | '/transfer/'
    | '/finances/ledgers/$id'
    | '/people/$id/report'
    | '/people/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/daybook'
    | '/analytics/advanced'
    | '/analytics/variety-breakdown'
    | '/incoming/$id'
    | '/incoming/edit-history'
    | '/outgoing/$id'
    | '/outgoing/edit-history'
    | '/reports/incoming'
    | '/reports/outgoing'
    | '/reports/transfer-stock'
    | '/settings/preferences'
    | '/settings/profile'
    | '/analytics'
    | '/finances'
    | '/incoming'
    | '/outgoing'
    | '/people'
    | '/settings'
    | '/transfer'
    | '/finances/ledgers/$id'
    | '/people/$id/report'
    | '/people/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/daybook'
    | '/_authenticated/analytics/advanced'
    | '/_authenticated/analytics/variety-breakdown'
    | '/_authenticated/incoming/$id'
    | '/_authenticated/incoming/edit-history'
    | '/_authenticated/outgoing/$id'
    | '/_authenticated/outgoing/edit-history'
    | '/_authenticated/people/$id'
    | '/_authenticated/reports/incoming'
    | '/_authenticated/reports/outgoing'
    | '/_authenticated/reports/transfer-stock'
    | '/_authenticated/settings/preferences'
    | '/_authenticated/settings/profile'
    | '/_authenticated/analytics/'
    | '/_authenticated/finances/'
    | '/_authenticated/incoming/'
    | '/_authenticated/outgoing/'
    | '/_authenticated/people/'
    | '/_authenticated/settings/'
    | '/_authenticated/transfer/'
    | '/_authenticated/finances/ledgers/$id'
    | '/_authenticated/people/$id/report'
    | '/_authenticated/people/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/daybook': {
      id: '/_authenticated/daybook'
      path: '/daybook'
      fullPath: '/daybook'
      preLoaderRoute: typeof AuthenticatedDaybookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfer/': {
      id: '/_authenticated/transfer/'
      path: '/transfer'
      fullPath: '/transfer/'
      preLoaderRoute: typeof AuthenticatedTransferIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outgoing/': {
      id: '/_authenticated/outgoing/'
      path: '/outgoing'
      fullPath: '/outgoing/'
      preLoaderRoute: typeof AuthenticatedOutgoingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incoming/': {
      id: '/_authenticated/incoming/'
      path: '/incoming'
      fullPath: '/incoming/'
      preLoaderRoute: typeof AuthenticatedIncomingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/': {
      id: '/_authenticated/finances/'
      path: '/finances'
      fullPath: '/finances/'
      preLoaderRoute: typeof AuthenticatedFinancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/preferences': {
      id: '/_authenticated/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/transfer-stock': {
      id: '/_authenticated/reports/transfer-stock'
      path: '/reports/transfer-stock'
      fullPath: '/reports/transfer-stock'
      preLoaderRoute: typeof AuthenticatedReportsTransferStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/outgoing': {
      id: '/_authenticated/reports/outgoing'
      path: '/reports/outgoing'
      fullPath: '/reports/outgoing'
      preLoaderRoute: typeof AuthenticatedReportsOutgoingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/incoming': {
      id: '/_authenticated/reports/incoming'
      path: '/reports/incoming'
      fullPath: '/reports/incoming'
      preLoaderRoute: typeof AuthenticatedReportsIncomingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/people/$id': {
      id: '/_authenticated/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof AuthenticatedPeopleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outgoing/edit-history': {
      id: '/_authenticated/outgoing/edit-history'
      path: '/outgoing/edit-history'
      fullPath: '/outgoing/edit-history'
      preLoaderRoute: typeof AuthenticatedOutgoingEditHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outgoing/$id': {
      id: '/_authenticated/outgoing/$id'
      path: '/outgoing/$id'
      fullPath: '/outgoing/$id'
      preLoaderRoute: typeof AuthenticatedOutgoingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incoming/edit-history': {
      id: '/_authenticated/incoming/edit-history'
      path: '/incoming/edit-history'
      fullPath: '/incoming/edit-history'
      preLoaderRoute: typeof AuthenticatedIncomingEditHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incoming/$id': {
      id: '/_authenticated/incoming/$id'
      path: '/incoming/$id'
      fullPath: '/incoming/$id'
      preLoaderRoute: typeof AuthenticatedIncomingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics/variety-breakdown': {
      id: '/_authenticated/analytics/variety-breakdown'
      path: '/analytics/variety-breakdown'
      fullPath: '/analytics/variety-breakdown'
      preLoaderRoute: typeof AuthenticatedAnalyticsVarietyBreakdownRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics/advanced': {
      id: '/_authenticated/analytics/advanced'
      path: '/analytics/advanced'
      fullPath: '/analytics/advanced'
      preLoaderRoute: typeof AuthenticatedAnalyticsAdvancedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/people/$id/': {
      id: '/_authenticated/people/$id/'
      path: '/'
      fullPath: '/people/$id/'
      preLoaderRoute: typeof AuthenticatedPeopleIdIndexRouteImport
      parentRoute: typeof AuthenticatedPeopleIdRoute
    }
    '/_authenticated/people/$id/report': {
      id: '/_authenticated/people/$id/report'
      path: '/report'
      fullPath: '/people/$id/report'
      preLoaderRoute: typeof AuthenticatedPeopleIdReportRouteImport
      parentRoute: typeof AuthenticatedPeopleIdRoute
    }
    '/_authenticated/finances/ledgers/$id': {
      id: '/_authenticated/finances/ledgers/$id'
      path: '/finances/ledgers/$id'
      fullPath: '/finances/ledgers/$id'
      preLoaderRoute: typeof AuthenticatedFinancesLedgersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedPeopleIdRouteChildren {
  AuthenticatedPeopleIdReportRoute: typeof AuthenticatedPeopleIdReportRoute
  AuthenticatedPeopleIdIndexRoute: typeof AuthenticatedPeopleIdIndexRoute
}

const AuthenticatedPeopleIdRouteChildren: AuthenticatedPeopleIdRouteChildren = {
  AuthenticatedPeopleIdReportRoute: AuthenticatedPeopleIdReportRoute,
  AuthenticatedPeopleIdIndexRoute: AuthenticatedPeopleIdIndexRoute,
}

const AuthenticatedPeopleIdRouteWithChildren =
  AuthenticatedPeopleIdRoute._addFileChildren(
    AuthenticatedPeopleIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDaybookRoute: typeof AuthenticatedDaybookRoute
  AuthenticatedAnalyticsAdvancedRoute: typeof AuthenticatedAnalyticsAdvancedRoute
  AuthenticatedAnalyticsVarietyBreakdownRoute: typeof AuthenticatedAnalyticsVarietyBreakdownRoute
  AuthenticatedIncomingIdRoute: typeof AuthenticatedIncomingIdRoute
  AuthenticatedIncomingEditHistoryRoute: typeof AuthenticatedIncomingEditHistoryRoute
  AuthenticatedOutgoingIdRoute: typeof AuthenticatedOutgoingIdRoute
  AuthenticatedOutgoingEditHistoryRoute: typeof AuthenticatedOutgoingEditHistoryRoute
  AuthenticatedPeopleIdRoute: typeof AuthenticatedPeopleIdRouteWithChildren
  AuthenticatedReportsIncomingRoute: typeof AuthenticatedReportsIncomingRoute
  AuthenticatedReportsOutgoingRoute: typeof AuthenticatedReportsOutgoingRoute
  AuthenticatedReportsTransferStockRoute: typeof AuthenticatedReportsTransferStockRoute
  AuthenticatedSettingsPreferencesRoute: typeof AuthenticatedSettingsPreferencesRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedFinancesIndexRoute: typeof AuthenticatedFinancesIndexRoute
  AuthenticatedIncomingIndexRoute: typeof AuthenticatedIncomingIndexRoute
  AuthenticatedOutgoingIndexRoute: typeof AuthenticatedOutgoingIndexRoute
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedTransferIndexRoute: typeof AuthenticatedTransferIndexRoute
  AuthenticatedFinancesLedgersIdRoute: typeof AuthenticatedFinancesLedgersIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDaybookRoute: AuthenticatedDaybookRoute,
  AuthenticatedAnalyticsAdvancedRoute: AuthenticatedAnalyticsAdvancedRoute,
  AuthenticatedAnalyticsVarietyBreakdownRoute:
    AuthenticatedAnalyticsVarietyBreakdownRoute,
  AuthenticatedIncomingIdRoute: AuthenticatedIncomingIdRoute,
  AuthenticatedIncomingEditHistoryRoute: AuthenticatedIncomingEditHistoryRoute,
  AuthenticatedOutgoingIdRoute: AuthenticatedOutgoingIdRoute,
  AuthenticatedOutgoingEditHistoryRoute: AuthenticatedOutgoingEditHistoryRoute,
  AuthenticatedPeopleIdRoute: AuthenticatedPeopleIdRouteWithChildren,
  AuthenticatedReportsIncomingRoute: AuthenticatedReportsIncomingRoute,
  AuthenticatedReportsOutgoingRoute: AuthenticatedReportsOutgoingRoute,
  AuthenticatedReportsTransferStockRoute:
    AuthenticatedReportsTransferStockRoute,
  AuthenticatedSettingsPreferencesRoute: AuthenticatedSettingsPreferencesRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedFinancesIndexRoute: AuthenticatedFinancesIndexRoute,
  AuthenticatedIncomingIndexRoute: AuthenticatedIncomingIndexRoute,
  AuthenticatedOutgoingIndexRoute: AuthenticatedOutgoingIndexRoute,
  AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedTransferIndexRoute: AuthenticatedTransferIndexRoute,
  AuthenticatedFinancesLedgersIdRoute: AuthenticatedFinancesLedgersIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
